[book]
authors = ["Yuri \"yublum\" Novais"]
language = "en"
multilingual = false
src = "src"
title = "SLAC Library Documentation"
description = "A simple linear algebra library for the C programming language."

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
